site_name: JUMA 文档中心
site_url: http://www.juma.io/doc/zh/
repo_url: https://github.com/JUMA-IO/JUMA_Docs
docs_dir: sources
theme_dir: theme/updocs
#theme: bootstrap
copyright: Copyright &copy; 2015, JUMA

pages:



- '低功耗蓝牙':
    - 'BLE入门': 'ble/first.md'
- 'BlueNRG方案': 
    - '概述':     'bluenrg/general.md'
    - '系统架构': 'bluenrg/arch.md'
    - 'ACI报文格式': 'bluenrg/aci.md'


# Add permalink for sharing
markdown_extensions:
    - toc:
        permalink: True
